### ISSUE TITLE
Ensure OCP 4.4 compliance

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-controller#445] opened 2020-03-06 20:49 UTC
Please close if this is a duplicate, but from discussions with QE, it's my understanding that there are elements of the controller that will have to be updated to ensure that we are deployable in a 4.4 cluster. Obviously we also still need to be backwards compatible to 3.7.

I wasn't sure if this was being tracked but we should expect ocp4.4 to land sometime in early April.

**Comment by jortel** [comment] 2020-03-06 21:00
Duplicate of: https://github.com/konveyor/mig-controller/issues/432

**Closed by jortel** 2020-03-06 21:00 UTC
