### ISSUE TITLE
Restic restart (mount-propagation workaround) only on OCP 3.7-3.9.

### ISSUE THREAD

**Issue by jortel** [konveyor/mig-controller#176] opened 2019-06-25 21:02 UTC
Perform Restic restart (mount-propagation workaround) only when cluster is OCP 3.7-3.9.

**Comment by djwhatle** [comment] 2020-05-28 00:14
Associated Jira: https://issues.redhat.com/browse/MIG-243

**Comment by djwhatle** [comment] 2020-05-28 14:39
After discussion today, came to the conclusion that we want to give the user some choice on whether to perform the Restic restart. 

## **Proposed logic**

**On OCP 3.7 (where Restic restart is always required):**

- Detect OCP version in mig-controller, then always run the Restic restart to save the user from hard to track PV data migration errors
- Use the method Alay mentioned for allowing Restic pods to schedule even on degraded nodes
- Migrating from version this old seems to be a corner case


**On OCP 3.9+ (where Restic restart may be required depending on feature gate setting)**

- It's hard to tell whether this mount propagation feature gate is enabled, so we will raise a validation warning on the MigPlan (meaning it will show up in UI) alerting users to this issue and telling them they may want to set a flag on mig-operator MigrationController CR enabling this step
- Default behavior will be to _not_ run Restic restart, but allow the user to turn on Restic restart via a flag on mig-operator `enable_restic_restart: True`

**Comment by djwhatle** [comment] 2020-05-28 14:47
One thing to be aware of for the above approach: we're going to be surfacing a warning condition for nearly every MigPlan that will be created (anything 3.9-3.11 as the src cluster)

**Comment by jmontleon** [comment] 2020-05-28 14:50
Can you expand on your comment about the 'mount propagation feature gate'? Is mount propagation not necessarily enabled on all OCP 3.9+ clusters?

**Comment by djwhatle** [comment] 2020-05-28 14:54
@jmontleon mount propagation seems to be a configurable feature until at least OCP 3.11 ([source](https://docs.openshift.com/container-platform/3.11/admin_guide/disabling_features.html))

For clusters not requiring the restart that have large numbers of nodes, running the Restic restart has a significant time penalty and sometimes fails due to nodes being in unhealthy state and being unable to get Pods back up successfully.

**Comment by jmontleon** [comment] 2020-05-28 14:56
Thanks. I was not aware the feature was optional.

**Comment by vconzola** [comment] 2020-05-28 17:11
@djwhatle I'm not thrilled about showing a warning on most every migration plan with a 3.9-3.11 source. I know from years of experience that most warnings are likely to be ignored, especially if there a number of them presented together (which seems to be the case often in migration plan validation).  How big of a time penalty are we talking about, and what happens if the user does not do a restart? Does the migration fail in a way that's difficult to diagnose? Also, will a user be able to set the restart flag from within the UI, or will they have to go out to the cli to do that?

**Comment by jmontleon** [comment] 2020-05-28 17:23
Maybe we can call the configuraiton option out in documentation.
* Leave the restart in by default
* add documentation to the effect that if you have mount propagation enabled on 3.9-3.11 or are using only 4.x you can set `restart_restic` to false in the MigrationController CR. Else leave it set to true. Or vice verse.

This way by default it works as it does now. If they disable it and break migrations it should be obvious why.

Or vice versa, disable the restarts by default and leave it as a common troubleshooting step to verify mount propagation is enabled or set the option to true... either way this new option seems like it will need documentation.

**Comment by djwhatle** [comment] 2020-05-28 17:41
> @djwhatle How big of a time penalty are we talking about,

It's not a lot of time for smaller clusters, but on larger real-world clusters with many nodes, it could take longer to complete. Especially on clusters with a where a node is in degraded state, the migration process can stall out during ResticRestart forever due to some Restic Pods not coming back up.

---

> and what happens if the user does not do a restart? Does the migration fail in a way that's difficult to diagnose? 

Yes, the Restic Backup of PVs will likely fail, and it will not be easy to determine the cause of failure. On affected cluster versions, the Restic restart is required for Restic to have visibility of PVs created since the Restic pod started.

---

> Also, will a user be able to set the restart flag from within the UI, or will they have to go out to the cli to do that?

In the design I am proposing, we'd set this on the flag on mig-operator CR, which is accessible from the OperatorHub portion of the OpenShift console, or from the CLI.

I like the idea of making this accessible from our UI, but am worried we don't have time to implement those changes before next Weds when we need this fix merged. The natural place would be to add a switch on a MigCluster asking the user if they have the `MountPropagation` feature gate turned on for that MigCluster, and we could run the restart based on that value.

I don't think the `host` MigCluster is editable from the Web UI, which is why I wasn't thinking of going this route.

---

Found this information on MountProp feature gate graduation ([source](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features))
Feature | Default | Stage | Since | Until
-- | -- | -- | -- | --
MountPropagation | false | Alpha | 1.8 | 1.9
MountPropagation | true | Beta | 1.10 | 1.11
MountPropagation | true | GA | 1.12 | -

**Comment by sseago** [comment] 2020-05-28 19:25
@djwhatle It does seem like the migcluster is the logical place for this. Just because there's one cluster that doesn't have mount propagation doesn't mean that *every* cluster we want to restart restic. At the very least, I guess even with a global "restart restic" flag set to true, we could still skip it for 4.x clusters, just like even if the global flag is false we'd still need to bounce restic for 3.7. If we put it on the migcluster, the usual way of configuring it for the host cluster is to have a setting on the MigrationController CR for the host cluster only. Since most customers will be running the host cluster on 4.x, having to tweak this value on the host cluster will only be needed for those few running 3.x hosts. That way for users running non-host-cluster 3.9-11 clusters, they could change the setting in the UI.

**Comment by djwhatle** [comment] 2020-05-28 20:04
I spoke with @eriknelson and @vconzola and it sounds like we aren't comfortable making UI changes in such a short time period (target next Weds).

**_However_**, after thinking on this more and considering what @sseago said above it seems clear to me that we should add this control to the MigCluster, given that "feature gates" of a cluster is a cluster-specific property and should be set on a per-cluster basis. 


**Is restic restart needed for users who have kept default feature gates?**
|OCP 3.7|OCP 3.9|OCP 3.11|OCP 4.1|OCP 4.2|OCP 4.3|OCP 4.4+|
|--------|--------|--------|--------|--------|--------|--------|
| _Yes_ | _Yes_| No| No| No| No| No| No|

## **Revised  logic**

**Goals**
1. Assume that most OCP users haven't changed the default featureGate setting for mountPropagation. Cater to the default/common case, but leave room for customization of settings when users have changed feature gates via MigCluster.
2. Allow user to add a `restartRestic: true/false` field to the MigCluster spec if user knows they need to override. Document when this will be necessary according to the table above. 
3. @vconzola requested that we do _not_ include a warning about _possibly_ needing to set 'resticRestart' on MigPlan validations, since this warning would nearly always show up. We can call out in documentation when this will be necessary.

**On OCP 3.7, 3.9 (where Restic restart is required when default gates used):**

- Detect OCP version in mig-controller. By default, run the Restic restart to save the user from hard to track PV data migration errors. 
- Allow the user to override by changing `restartRestic: bool` field on the MigCluster CR
- Use the method Alay mentioned for allowing Restic pods to schedule even on degraded nodes

**On OCP 3.10+, 4.x(where Restic restart may be required depending on feature gate setting)**

- Default behavior will be to not run Restic restart
- Allow the user to override by changing `restartRestic: bool` field on the MigCluster CR
- Use the method Alay mentioned for allowing Restic pods to schedule even on degraded nodes

**Closed** 2020-06-02 15:09 UTC
Labels: enhancement, release-1.2.1
